name: Daily Auto Commit - 24f2008315@ds.study.iitm.ac.in

on:
  schedule:
    - cron: "17 14 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Commit Step
        run: |
          echo "Last run: $(date)" >> daily-log.txt
          git config --global user.name "24F2008315"
          git config --global user.email "24f2008315@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Daily scheduled commit"
          git push
